name: venv
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.3.0=h27087fc_1
  - blas=2.16=mkl
  - brotli-python=1.0.9=py39h5a03fae_7
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cpython=3.9.23=py39hd8ed1ab_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=5.0.1=h964e5f1_2
  - filelock=3.19.1=pyhd8ed1ab_0
  - freetype=2.13.3=h4a9f257_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py39h78fa15d_0
  - gnutls=3.6.13=h85f3911_1
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libblas=3.8.0=16_mkl
  - libcblas=3.8.0=16_mkl
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=11.2.0=h1234567_1
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.8.0=16_mkl
  - liblapacke=3.8.0=16_mkl
  - libnpp=12.0.2.50=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libva=2.21.0=hd590300_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2020.2=256
  - mpc=1.2.1=h9f54685_0
  - mpfr=4.1.0=h9202a9a_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nettle=3.6=he412f7d_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.24=h0dcde21_1
  - python_abi=3.9=2_cp39
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - svt-av1=1.1.0=h27087fc_1
  - tk=8.6.15=h54e0aa7_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=py39h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.19.0=py39h5eee18b_0
  - zstd=1.5.2=h8a70e8d_1
  - pip:
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bert-score==0.3.13
      - bitsandbytes==0.48.2
      - bleach==6.2.0
      - cachetools==6.2.2
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.1.8
      - comm==0.2.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - dacite==1.9.2
      - datasets==4.4.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - distro==1.9.0
      - docstring-parser==0.17.0
      - eval-type-backport==0.2.2
      - evaluate==0.4.6
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filetype==1.2.0
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2024.3.1
      - gcsfs==2024.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.1
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.6.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imagehash==4.3.1
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipykernel==6.31.0
      - ipython==8.18.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.7
      - lark==1.3.1
      - llvmlite==0.43.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - minify-html==0.18.1
      - mistune==3.1.4
      - mizani==0.11.4
      - multidict==6.7.0
      - multimethod==1.12
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nltk==3.9.2
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - openai==1.6.1
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.1.4
      - pandocfilters==1.5.1
      - parso==0.8.5
      - patsy==1.0.2
      - peft==0.7.1
      - pexpect==4.9.0
      - phik==0.12.5
      - pillow==11.3.0
      - platformdirs==4.4.0
      - plotnine==0.13.6
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - psutil==7.1.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - puremagic==1.30
      - pyarrow==21.0.0
      - pyarrow-hotfix==0.7
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyreft==0.1.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyvene==0.1.8
      - pywavelets==1.6.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.36.2
      - regex==2025.10.23
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.2.2
      - scipy==1.11.4
      - seaborn==0.12.2
      - send2trash==1.8.3
      - sentence-transformers==2.3.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.46.0
      - shtab==1.7.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - statsmodels==0.14.5
      - sympy==1.13.1
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.20.3
      - tomli==2.3.0
      - torch==2.2.1
      - torchaudio==2.2.1
      - torchvision==0.17.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.45.1
      - triton==2.2.0
      - trl==0.7.7
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tyro==0.9.35
      - tzdata==2025.2
      - uri-template==1.3.0
      - visions==0.8.1
      - wandb==0.23.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - wordcloud==1.9.4
      - xxhash==3.6.0
      - yarl==1.22.0
      - ydata-profiling==4.17.0
      - zipp==3.23.0
prefix: /DATA/cs25resch11006/miniconda3/envs/venv
